plugins:
  knowledge_base_enabled:
    default: true
    client: true
  knowledge_base_title:
    default: 'Knowledge Base'
    client: true
  knowledge_base_description:
    default: ''
    client: true
